name: CI
on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
      artifact-directory: ./bin
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --configuration Release --no-build
      working-directory: ${{env.working-directory}}
    - name: Inspect
      uses: actions/checkout@v2
      uses: microsoft/ApplicationInspector-Action@v1
      uses: actions/upload-artifact@v2
        with:
            name: AppInspectorResults
            path: AppInspectorResults.json